SMGJ/Models/TIPI.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMGJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPI()
        {
            this.GJEDHIs = new HashSet<GJEDHI>();
        }
    
        public int ID { get; set; }
        public string Emertimi { get; set; }
        public Nullable<System.DateTime> Krijuar { get; set; }
        public Nullable<int> KrijuarNga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GJEDHI> GJEDHIs { get; set; }
    }
}

SMGJ/Controllers/TipiController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using SMGJ.Models;

namespace SMGJ.Controllers
{   [CustomAuthorizeAttribute]
    public class TipiController : BaseController
    {
        SMGJDB db = new SMGJDB();
        // GET: Tipi
        public ActionResult Index()
        {
            List<TIPI> model = db.TIPIs.ToList();
            return View(model);
        }

        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            var tipi = new TIPI();
            if (id == 0)
                return View(tipi);
            else
                    return View(db.TIPIs.Where(x => x.ID == id).FirstOrDefault<TIPI>());
        }

        [HttpPost]
        public async Task<ActionResult> AddOrEdit(TIPI emp)
        {
            var user = await GetUser();
            MessageJs returnmodel = new MessageJs();
            TIPI tip = new TIPI();
            if (emp.ID != 0)
            {
                tip = db.TIPIs.Find(emp.ID);
            }
            tip.ID = emp.ID;
            tip.Emertimi = emp.Emertimi;
            tip.Krijuar = DateTime.Now;
            tip.KrijuarNga = user.ID;


            var exist = db.TIPIs.Where(e => e.Emertimi.ToLower().Trim() == emp.Emertimi.ToLower().Trim()).Any();
            if (exist)
            {
                returnmodel.status = false;
                returnmodel.Mesazhi = "Këto tipe ekzistojnë!";
                return Json(returnmodel, JsonRequestBehavior.DenyGet);
            }  

            if (emp.ID == 0)
            {
                db.TIPIs.Add(tip);
            }
            else
            {
                db.Entry(tip).State = EntityState.Modified;
            }
                
                await db.SaveChangesAsync();
                returnmodel.status = true;
                returnmodel.Mesazhi = "Të dhënat e tipit u regjistruan me sukses";
                return Json(returnmodel, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public async Task<ActionResult> Delete(TIPI model)
        {
            var user = await GetUser();
            MessageJs returnmodel = new MessageJs();
             bool exists1 = db.GJEDHIs.Any(q => q.TipiID == model.ID);

            if(exists1)
            {
                returnmodel.status = false;
                returnmodel.Mesazhi = "Tipi i gjedhit nuk mund të fshihet";
                return Json(returnmodel, JsonRequestBehavior.DenyGet);
            }
            try
            {
                TIPI tipi = db.TIPIs.Find(model.ID);
                db.TIPIs.Remove(tipi);
                await db.SaveChangesAsync();
                returnmodel.status = true;
                returnmodel.Mesazhi = "Tipi i gjedhit është fshirë me sukses";
                return Json(returnmodel, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                returnmodel.status = false;
                returnmodel.Mesazhi = "Ka ndodhur një gabim";
                return Json(returnmodel, JsonRequestBehavior.DenyGet);
            }
        }

    }
}

SMGJ/Views/Tipi/AddOrEdit.cshtml
@model SMGJ.Models.TIPI
@{
    Layout = null;
}

@using (Html.BeginForm("AddOrEdit", "Tipi", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
{
    @Html.HiddenFor(model => model.ID)
    <div class="form-group">
        @Html.LabelFor(model => model.Emertimi, new { @class = "control-label" })
        @Html.EditorFor(model => model.Emertimi, new { htmlAttributes = new { @class = "form-control" } })
    </div>

    <div class="form-group">
        <input type="submit" value="Edit/Regjistro" class="btn btn-primary" />
    </div>
}

SMGJ/Views/Tipi/Index.cshtml
@model IEnumerable<SMGJ.Models.TIPI>
@using SMGJ.Models
@{
    ViewBag.Title = "Index";
    SMGJDB db = new SMGJDB();
}

<h2 style="font-family: Georgia, serif "><center>TIPI</center></h2>
<div class="row">
    <div class="col-md-12">
        <a class="btn btn-green" style="margin-bottom:10px" onclick="PopupForm('@Url.Action("AddOrEdit","Tipi")')"><i class="fa fa-plus"></i> Regjistro</a>
    </div>
</div>
<div class="row margin-top-15 ">
    <div class="col-md-12">
        <div class="panel panel-white">
            <div class="panel-body">
                <table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
                    <thead>
                        <tr>
                            
                            <th>Em&euml;rtimi</th>
                            <th>Krijuar</th>
                            <th class="hidden-xs"> Krijuar nga</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            var user = db.USERs.Find(item.KrijuarNga);
                            <tr>
                                
                                <td class="hidden-xs">
                                    @item.Emertimi
                                </td>
                                <td>@item.Krijuar.Value.ToString("dd/MMMM/yyyy")</td>
                                <td>@user.Emri @user.Mbiemri</td>
                                <td>
                                    <div class="visible-md visible-lg hidden-sm hidden-xs">
                                        <a class="btn btn-transparent btn-xs"  onclick="PopupForm('@Url.Action("AddOrEdit","Tipi",new { id = item.ID})')" tooltip-placement="top" tooltip="Edit"><i class="fa fa-pencil"></i></a>
                                        <a onclick="deletemenu(this)" data-menuid="@item.ID" class="btn btn-transparent btn-xs tooltips" tooltip-placement="top" tooltip="Remove"><i class="fa fa-remove"></i></a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>

@section scripts {
    <script>
        var Popup;
        function PopupForm(url) {
            var formDiv = $('<div/>');
            $.get(url)
                .done(function (response) {
                    formDiv.html(response);

                    Popup = formDiv.dialog({
                        autoOpen: true,
                        draggable: false,
                        modal: true,
                        resizable: false,
                        show: {
                            effect: 'fade',
                            duration: 1000
                        },
                        title: 'Plotëso',
                        height: 180,
                        width: 400,
                        close: function () {
                            Popup.dialog('destroy').remove();
                            location.reload();
                        }
                    });
                });
        }

        function SubmitForm(form) {
            if ($(form).valid()) {
                $(form).submit(function (e) {
                    e.preventDefault();
                     });
                    $.ajax({
                        type: "POST",
                        url: form.action,
                        data: $(form).serialize(),
                        success: function (rs) {
                            if (rs.status) {
                            swal({ title: "Sukses", text: rs.Mesazhi, type: "success" },
                                function () {
                                    location.reload();
                                }
                            );
                        }
                            else {
                                swal({ title: "Gabim", text: rs.Mesazhi, type: "error" },
                                function () {
                                    location.reload();
                                }
                            );
                            }
                        }
                    });
            }
            return false;
        }

        var deletemenu = function (btn) {
            var obj = { ID: $(btn).data("menuid") };
            swal({
                title: "Kujdes!!!",
                text: "Jeni duke fshirë të dhëna nga Baza",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Po!",
                cancelButtonText: "Jo!",
                closeOnConfirm: false,
                closeOnCancel: false
            }, function (isConfirm) {
                    if (isConfirm) {
                    $.ajax({
                    url: "@Url.Action("Delete", "Tipi")",
                    cache: false,
                    type: "POST",
                    dataType: "json",
                    data: obj,
                    success: function (rs) {
                        if (rs.status) {
                            swal({ title: "Deleted", text: rs.Mesazhi, type: "success" },
                                function () {
                                    location.reload();
                                }
                            );
                        }
                        else {
                            swal("Gabim!",
                                rs.Mesazhi,
                                "info");
                        }
                    },
                    error: function (jqXHR, error, errorThrown) {
                        if (jqXHR.status && jqXHR.status == 400) {
                            console.log(jqXHR.responseText);
                        } else {
                            console.log("Something went wrong");
                        }
                    }
                });
                } else {
                    swal("Anuluar", "Fshirja e të dhënave është anuluar :)", "error");
                }
            });

        };
    </script>
}