SMGJ/Models/KONTAMINIMI.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMGJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KONTAMINIMI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KONTAMINIMI()
        {
            this.QUMESHTIs = new HashSet<QUMESHTI>();
        }
    
        public int ID { get; set; }
        public string Vlera { get; set; }
        public string Niveli { get; set; }
        public Nullable<System.DateTime> Krijuar { get; set; }
        public Nullable<int> KrijuarNga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUMESHTI> QUMESHTIs { get; set; }
    }
}

SMGJ/Controllers/KontaminimiController.cs
using SMGJ.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using static SMGJ.Helpers.Enums;

namespace SMGJ.Controllers
{   [CustomAuthorizeAttribute]
    public class KONTAMINIMIController : BaseController
    {
        SMGJDB db = new SMGJDB();


        // GET: Kontaminimi
        public async Task<ActionResult> Index()
        {

            
            var user = await GetUser();

            var kontaminimi = (from k in db.KONTAMINIMIs select k).AsEnumerable();
            return View(kontaminimi);
        }

        public async Task<ActionResult> Create()
        {
            //var x = Url.Content();
            var user = await GetUser();
            KONTAMINIMI model = new KONTAMINIMI();
            var niveliList = EnumsToSelectList<Nivelet_e_kontaminimit>.GetSelectList();
            var lista = new List<SelectListItem>();
            foreach (var item in niveliList)
                lista.Add(new SelectListItem { Value = item.Value, Text = item.Text, Selected = false });
            ViewBag.Nivelet = lista;
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Create(KONTAMINIMI model)
        {
            var user = await GetUser();
            MessageJs returnmodel = new MessageJs();
            if (ModelState.IsValid)
            {
                try
                {
                    KONTAMINIMI new_model = new KONTAMINIMI();
                    var test = from O_K in db.KONTAMINIMIs
                               where O_K.Niveli == model.Niveli && O_K.Vlera == model.Vlera
                               select new { O_K.ID };
                    if(test.Count() != 0)
                    {
                        returnmodel.Mesazhi = "Këto vlera të kontaminimit ekzistojnë në databazë!";
                        return Json(returnmodel, JsonRequestBehavior.DenyGet);
                    }

                    
                    new_model.KrijuarNga = user.ID;
                    new_model.Krijuar = DateTime.Now;
                    new_model.Vlera = model.Vlera;
                    new_model.Niveli = model.Niveli;

                    db.KONTAMINIMIs.Add(new_model);
                    await db.SaveChangesAsync();
                    returnmodel.status = true;
                    returnmodel.Mesazhi = "Kontaminimi u regjistrua me sukses";
                    return Json(returnmodel, JsonRequestBehavior.AllowGet);
                }
                catch
                {
                    returnmodel.status = false;
                    returnmodel.Mesazhi = "Ka ndodhur nje gabim";
                    return Json(returnmodel, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                returnmodel.status = false;
                returnmodel.Mesazhi = "Modeli nuk eshte valid";
                return Json(returnmodel, JsonRequestBehavior.DenyGet);
            }
        }



        [HttpPost]
        public async Task<ActionResult> DeleteKont(KONTAMINIMI model)
        {
            var user = await GetUser();
            MessageJs returnmodel = new MessageJs();
            try
            {
                KONTAMINIMI kontaminimi = db.KONTAMINIMIs.Find(model.ID);
                //var test = from M in db.MENUs
                //           join MR in db.MENU_ROLI on M.ID equals MR.MenuID
                //           select new { ID = M.ID, Emertimi = M.Emertimi, MR_ID = MR.MenuID };

                var test = from K in db.KONTAMINIMIs
                           join Q in db.QUMESHTIs on K.ID equals Q.KontaminimiID
                           select new { ID = K.ID};
                var z = (from t in test select t.ID).ToList();

                if (z.Contains(model.ID))
                {
                    //Nuk lejohet 
                    returnmodel.Mesazhi = "Ky kontaminim nuk mund të fshihet sepse ekziston qumesht qe permban kete kontaminim";
                    returnmodel.status = false;
                    return Json(returnmodel, JsonRequestBehavior.DenyGet);

                }
                else
                {
                    //Lejohet
                    db.KONTAMINIMIs.Remove(kontaminimi);
                    await db.SaveChangesAsync();
                    returnmodel.status = true;
                    return Json(returnmodel, JsonRequestBehavior.AllowGet);
                }

                
             

             

            }
            catch (Exception)
            {
                returnmodel.status = false;
                returnmodel.Mesazhi = "Ka ndodhur nje gabim";
                return Json(returnmodel, JsonRequestBehavior.DenyGet);
            }
        }

        public async Task<ActionResult> Edit(int? id)
        {
            var user = await GetUser();
            KONTAMINIMI model = new KONTAMINIMI();
            //var user = await GetUser();
            //KONTAMINIMI model = new KONTAMINIMI();

            var niveliList = EnumsToSelectList<Nivelet_e_kontaminimit>.GetSelectList();
            var lista = new List<SelectListItem>();
            foreach (var item in niveliList)
                lista.Add(new SelectListItem { Value = item.Value, Text = item.Text, Selected = false });
            ViewBag.Nivelet = lista;
            if (id != null)
            {
                //int x = Int32.Parse(Decrypt(id.Value.ToString()));
                model = db.KONTAMINIMIs.Find(id.Value);
            }
            return View(model);
        }


        public async Task<ActionResult> Edit1(string id)
        {
            var user = await GetUser();
            KONTAMINIMI model = new KONTAMINIMI();



            //var user = await GetUser();
            //KONTAMINIMI model = new KONTAMINIMI();

            var niveliList = EnumsToSelectList<Nivelet_e_kontaminimit>.GetSelectList();
            var lista = new List<SelectListItem>();
            foreach (var item in niveliList)
                lista.Add(new SelectListItem { Value = item.Value, Text = item.Text, Selected = false });
            ViewBag.Nivelet = lista;
            if (id != null)
            {
                int x = Int32.Parse(Decrypt(id));
                model = db.KONTAMINIMIs.Find(x);
            }
            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> Edit(KONTAMINIMI model)
        {
            var user = await GetUser();
            MessageJs returnmodel = new MessageJs();
            if (ModelState.IsValid)
            {
                try
                {
                    KONTAMINIMI new_model = db.KONTAMINIMIs.Find(model.ID);

                    /*
                     *Ekziston nje qumesht me kete kontaminim keshtu qe nuk mund te ndryshohet 
                     * */
                    var test1 = from K in db.KONTAMINIMIs
                                join Q in db.QUMESHTIs on K.ID equals Q.KontaminimiID
                                select new { ID = K.ID };
                    var z = (from t in test1 select t.ID).ToList();
                    if (z.Contains(model.ID))
                    {
                        returnmodel.Mesazhi = "Ky kontaminim nuk mund të fshihet, sepse ekziston qumesht qe permban kete kontaminim";
                        returnmodel.status = false;
                        return Json(returnmodel, JsonRequestBehavior.DenyGet);
                    }


                    var test = from O_K in db.KONTAMINIMIs
                               where O_K.Niveli == model.Niveli && O_K.Vlera == model.Vlera
                               select new { O_K.ID };
                    /*
                     *Ekziston nje kontaminim me keto vlera keshtu qe nuk mund te ndryshohet 
                     * */
                    if (test.Count() != 0)
                    {
                        returnmodel.Mesazhi = "Këto vlera të kontaminimit ekzistojnë!";
                        return Json(returnmodel, JsonRequestBehavior.DenyGet);
                    }

                    
                    //new_model.Controller = model.Controller;
                    //new_model.Action_Metoda = model.Action_Metoda;
                    //new_model.Aktiv = model.Aktiv;
                    //new_model.Emertimi = model.Emertimi;
                    //new_model.Renditja = model.Renditja;
                    //bone update

                    new_model.KrijuarNga = user.ID;
                    new_model.Krijuar = DateTime.Now;
                    new_model.Vlera = model.Vlera;
                    new_model.Niveli = model.Niveli;
                    db.Entry(new_model).State = EntityState.Modified;
                    //ruaj te dhenat
                    await db.SaveChangesAsync();
                    returnmodel.status = true;
                    returnmodel.Mesazhi = "Te dhenat e kontaminimit u edituan me sukses";
                    return Json(returnmodel, JsonRequestBehavior.AllowGet);
                    //return Json(returnmodel, JsonRequestBehavior.AllowGet);
                }
                catch
                {
                    returnmodel.status = false;
                    returnmodel.Mesazhi = "Ka ndodhur nje gabim";
                    return Json(returnmodel, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                returnmodel.status = false;
                returnmodel.Mesazhi = "Modeli nuk eshte valid";
                return Json(returnmodel, JsonRequestBehavior.DenyGet);
            }
        }

    }// End of class
}// End of namespace 

SMGJ/Views/Kontaminimi/Edit.cshtml
@model SMGJ.Models.KONTAMINIMI
@{
    ViewBag.Title = "Edit";
    var nivelet = (List<SelectListItem>)ViewBag.Nivelet;
}
@Html.HiddenFor(k => k.ID)
<head>
    <link href="~/Content/theme/vendor/sweetalert/sweet-alert.css" rel="stylesheet" media="screen">
    <link href="~/Content/theme/vendor/sweetalert/ie9.css" rel="stylesheet" media="screen">
    <link href="~/Content/theme/vendor/toastr/toastr.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/theme/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
</head>
<section id="page-title">
    <div class="row">
        <div class="col-sm-8">
            <h1 class="mainTitle" style="color:royalblue; font-family: Shakespeare, 'Times New Roman', Times, serif">Editimi i kontaminimit</h1>
        </div>
    </div>
</section>
<div class="container-fluid container-fullw bg-white">
    <div class="panel panel-white">
        <div class="panel-body">
            <form id="forma">

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">
                                Vlera <span class="symbol required" aria-required="true"></span>
                            </label>
                            @Html.TextBoxFor(k => k.Vlera, new { @class = "form-control", @placeholder = "Shkruani vlerën e kontaminimit" })

                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">
                                Niveli <span class="symbol required" aria-required="true"></span>
                            </label>
                            <br />
                            @{ var niveli = Model.Niveli;
                                var indeksi = nivelet.FindIndex(l => l.Text == niveli);
                                nivelet.RemoveAt(indeksi);
                                }
                            @*@Html.TextBoxFor(k => k.Niveli, new { @class = "form-control", @placeholder = "" })*@
                            @*@Html.DropDownList("Zgjedh", nivelet, new { @class = "@form-control select2", @name = "dropdown", @Id = "Niveli" })*@
                            @Html.DropDownListFor(n => nivelet, nivelet, niveli, (new { @class = "form-control select2", @Id = "Niveli" }))
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="panel-footer clearfix">
            <div class="col-md-12">
                <button class="btn btn-primary btn-wide pull-right" type="button" onclick="edito(this)">
                    Ndrysho <i class="fa fa-arrow-circle-right"></i>
                </button>

                <a href="@Url.Action("Index","KONTAMINIMI")" class="btn btn-danger btn-wide">Anulo <i class="fa fa-arrow-circle-left"></i></a>
                @*<button class="btn btn-primary btn-wide pull-right" type="button" onclick="@Url.Action("Index","KONTAMINIMI")">
                        Cancel <i class="fa fa-crosshairs"></i>
                    </button>

                            <a href="@Url.Action("Index","KONTAMINIMI")" class="btn btn-transparent btn-xs" tooltip-placement="top" tooltip="Edit"><i class="fa fa-pencil"></i></a>*@
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        runValidator1 = function () {
            var form1 = $('#forma');
            var errorHandler1 = $('.errorHandler', form1);
            var successHandler1 = $('.successHandler', form1);
            $('#forma').validate({
                errorElement: "span", // contain the error msg in a span tag
                errorClass: 'help-block',
                errorPlacement: function (error, element) { // render error placement for each input type
                    if (element.attr("type") == "radio" || element.attr("type") == "checkbox") { // for chosen elements, need to insert the error after the chosen container
                        error.insertAfter($(element).closest('.form-group').children('div').children().last());
                    } else if (element.attr("name") == "dd" || element.attr("name") == "mm" || element.attr("name") == "yyyy") {
                        error.insertAfter($(element).closest('.form-group').children('div'));
                    } else {
                        error.insertAfter(element);
                        // for other inputs, just perform default behavior
                    }
                },
                ignore: "",
                rules: {
                    Controller: {
                        required: true
                    },
                    Action_Metoda: {
                        required: true
                    },
                    Emertimi: {
                        required: true
                    },

                    Renditja: {
                        required: true,
                        number: true

                    },
                    Vlera: {
                        required: true,
                        number: true
                    },
                    Niveli: {
                        required: true,
                    },
                },
                invalidHandler: function (event, validator) { //display error alert on form submit
                    successHandler1.hide();
                    errorHandler1.show();
                },
                highlight: function (element) {
                    $(element).closest('.help-block').removeClass('valid');
                    // display OK icon
                    $(element).closest('.form-group').removeClass('has-success').addClass('has-error').find('.symbol').removeClass('ok').addClass('required');
                    // add the Bootstrap error class to the control group
                },
                unhighlight: function (element) { // revert the change done by hightlight
                    $(element).closest('.form-group').removeClass('has-error');
                    // set error class to the control group
                },
                success: function (label, element) {
                    label.addClass('help-block valid');
                    // mark the current input as valid and display OK icon
                    $(element).closest('.form-group').removeClass('has-error').addClass('has-success').find('.symbol').removeClass('required').addClass('ok');
                },
                submitHandler: function (form) {
                    successHandler1.show();
                    errorHandler1.hide();
                    // submit form
                    //$('#form').submit();
                }
            });
        };
        var edito = function (btn) {
                runValidator1();
                if ($("#forma").valid() === true) {
                    var obj = {
                    //Controller: $("#Controller").val(),
                    //Action_Metoda: $("#Action_Metoda").val(),
                    //Emertimi: $("#Emertimi").val(),
                    //Renditja: $("#Renditja").val(),
                        //Aktiv: $('#Aktiv').is(':checked')
                        Vlera: $("#Vlera").val(),
                        Niveli: $("#Niveli :selected").text()
                };
                var url_redirect = '@Url.Action("Index", "KONTAMINIMI")';
                $.ajax({
                    url: "@Url.Action("Edit", "KONTAMINIMI")",
                    cache: false,
                    type: "POST",
                    dataType: "json",
                    data: obj,
                    success: function (rs) {
                        if (rs.status) {
                            swal({ title: "U ndryshua!", text: "Kontaminimi që keni zgjedhur është ndryshuar me sukses!", type: "success" }, function () {
                                //location.reload()
                                window.location.href = url_redirect;

                            });
                        }
                        else {
                            //alert(rs.Mesazhi, "error");
                            swal("Gabim në ndërrim", rs.Mesazhi, "error");
                        }

                    },
                    error: function (jqXHR, error, errorThrown) {
                        if (jqXHR.status && jqXHR.status == 400) {
                            console.log(jqXHR.responseText);
                            swal("Anulim!", "Ka ndodhur një problem në ndërrim! Ju lutemi provoni përsëri!", "error")
                        } else {
                            swal("Anulim!", "Ka ndodhur një problem në ndërrim! Ju lutemi provoni përsëri!", "error")
                            console.log("Something went wrong");
                        }
                    }
                });
            }

        };


    </script>
    <script src="~/Content/theme/vendor/sweetalert/sweet-alert.min.js"></script>
    <script src="~/Content/theme/vendor/toastr/toastr.min.js"></script>
    <script src="~/Content/theme/assets/js/main.js"></script>
    <script src="~/Content/theme/assets/js/ui-notifications.js"></script>
    <script src="~/Content/theme/vendor/select2/select2.min.js"></script>
    <link href="~/Content/theme/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
    <script>
        jQuery(document).ready(function () {

            $(".select2").select2(
                {
                    width: '100%'
                });
        })
    </script>

}


SMGJ/Views/Kontaminimi/Index.cshtml
@model IEnumerable<SMGJ.Models.KONTAMINIMI>
@using SMGJ.Models
@using SMGJ.Controllers
@{
    ViewBag.Title = "Index";
    //int t = 1;
    SMGJDB db = new SMGJDB();
}
<head>
    <link href="~/Content/theme/vendor/sweetalert/sweet-alert.css" rel="stylesheet" media="screen">
    <link href="~/Content/theme/vendor/sweetalert/ie9.css" rel="stylesheet" media="screen">
    <link href="~/Content/theme/vendor/toastr/toastr.min.css" rel="stylesheet" media="screen">
</head>
<section id="page-title">
    <div class="row">
        <div class="col-sm-8">
            <h1 class="mainTitle" style="color:royalblue; font-family: Shakespeare, 'Times New Roman', Times, serif">Lista e kontaminive të qumështit </h1>
        </div>
    </div>
</section>
<div class="container-fluid container-fullw bg-white">
    <div class="row">
        <div class="col-md-12">
            <a href="@Url.Action("Create","Kontaminimi")" class="btn btn-green">Regjistro</a>
        </div>
    </div>
    <div class="row margin-top-15 ">
        <div class="col-md-12">
            <div class="panel panel-white">
                <div class="panel-heading">
                    <h5 class="panel-title">Lista e kontaminimeve</h5>
                </div>
                <div class="panel-body">
                    <table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
                        <thead>
                            <tr>
                                
                                <th class="hidden-xs">Vlera</th>

                                <th>
                                    Niveli
                                </th>
                                <th class="hidden-xs"> Krijuar</th>
                                <th>
                                    Krijuar nga
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                foreach (var item in Model)
                                {
                                    <tr name="rreshtat" contenteditable="false">
                                        
                                        <td class="hidden-xs">
                                            @item.Vlera
                                        </td>
                                        <td>@item.Niveli</td>
                                        <td class="hidden-xs">
                                            @*@{
                                                    var klasa = "success";
                                                    var pershktimi = "Aktive";
                                                    if (item.Aktiv != true)
                                                    {
                                                        klasa = "danger";
                                                        pershktimi = "Pasive";
                                                    }
                                                }*@
                                            @*<span class="label label-sm label-@klasa">@pershktimi</span>*@
                                            @item.Krijuar.Value.ToString("dd/MM/yyyy")
                                        </td>
                                        <td>
                                            @{
                                                
                                                var user = db.USERs.Find(item.KrijuarNga);
                                        }
                                        @user.Emri @user.Mbiemri
                                    </td>
                                    <td>
                                        <div class="visible-md visible-lg hidden-sm hidden-xs">
                                            <a href="@Url.Action("Edit","KONTAMINIMI" , new {id=(item.ID)})" class="btn btn-transparent btn-xs tooltips" tooltip-placement="top" tooltip="Edit"><i class="fa fa-pencil"></i></a>
                                            @*<a href="@Url.Action("Edit","KONTAMINIMI" , new {id=(BaseController.Encrypt(item.ID.ToString()))})" class="btn btn-transparent btn-primary btn-xs" tooltip-placement="top" tooltip="Edit"><i class="fa fa-pencil"></i></a>*@
                                            <a onclick="deletemenu(this)" data-kontid="@item.ID" class="btn btn-transparent btn-xs tooltips" tooltip-placement="top" tooltip="Remove"><i class="fa fa-times fa fa-white"></i></a>
                                        </div>
                                    </td>

                                </tr>
                            }

                            @*<tr>
                                    <td><input type="text" name="New_Id" placeholder=2 /></td>
                                    <td><input type="text" placeholder=2 /></td>
                                    <td><input type="text" placeholder=3 /></td>
                                    <td><input type="text" placeholder=4 /></td>
                                    <td><input type="text" placeholder=5 /></td>
                                    <td><button>Shto Rreshtin</button></td>
                                </tr>*@
                            }

                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
</div>

@section Scripts{

    <script src="~/Content/theme/vendor/sweetalert/sweet-alert.min.js"></script>
    <script src="~/Content/theme/vendor/toastr/toastr.min.js"></script>
    <script src="~/Content/theme/assets/js/main.js"></script>
    <script src="~/Content/theme/assets/js/ui-notifications.js"></script>
    <script>


        var deletemenu = function (btn) {
            //alert("heelo");


            @*//alert($(btn).data("kontid"))
             $.ajax({
                    url: "@Url.Action("DeleteKont", "KONTAMINIMI")",
                    cache: false,
                    type: "POST",
                    dataType: "json",
                    data: obj,
                    success: function (rs) {
                        if (rs.status) {
                            /*swal("Deleted!", "Your imaginary file has been deleted.", "success");*/

                            //window.setTimeout(function () { location.reload() }, 2000);
                            location.reload();
                        } else {
                            //alert("This cannot be deleted");
                            alert(rs.Mesazhi)
                            //swal("Cancelled", "Your imaginary file is safe :)", "error");
                        }
                    },
                    error: function (jqXHR, error, errorThrown) {
                        if (jqXHR.status && jqXHR.status == 400) {
                            console.log(jqXHR.responseText);
                        }
                        else {
                            swal("Error deleting!", "Please try again", "error");
                        }
                    }
                }); //end ajax*@
            /*var obj = { ID: $(btn).data("menuid") };*/
            //var obj = { ID: $(btn).data("kontid") };
            swal({
                    title: "A jeni i sigurt?",
                    text: "Ju nuk do të jeni në gjendje të riktheni kontaminimin e zgjedhur!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Po, fshije!",
                    cancelButtonText: "Jo, anulo!",
                    closeOnConfirm: false,
                    closeOnCancel: false
                }, //end swal
                    function (isConfirm) {
                        if (isConfirm) {
                            var obj = { ID: $(btn).data("kontid") };
                            $.ajax({
                                url: "@Url.Action("DeleteKont", "KONTAMINIMI")",
                                cache: false,
                                type: "POST",
                                dataType: "json",
                                data: obj,
                                success: function (rs) {
                                    if (rs.status) {
                                        swal({ title: "Deleted!", text: "Kontaminimi i zgjedhur është fshirë me sukses!", type: "success" },  function () {
                                            location.reload()
                                        });

                                        //window.setTimeout(function () { location.reload() }, 2000);
                                        //location.reload();
                                    } else {
                                        //alert("This cannot be deleted");
                                        swal("Anulim!", rs.Mesazhi, "error");
                                    }
                                },
                                error: function (jqXHR, error, errorThrown) {
                                    if (jqXHR.status && jqXHR.status == 400) {
                                        console.log(jqXHR.responseText);
                                    }
                                    else {
                                        swal("Gabim në fshirje!", "Ju lutemi provoni përsëri!", "error");
                                    }
                                }
                            }); //end ajax
                        } else {
                            swal("Anulim!", "Kontaminimi i zgjedhur nuk është fshirë!", "error");
                        }
                    });
        } //end delete
    </script>

}

