SMGJ/Models/LAGESHTIA_AJRIT.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMGJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAGESHTIA_AJRIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LAGESHTIA_AJRIT()
        {
            this.GJEDHAT_PARAMETRAT = new HashSet<GJEDHAT_PARAMETRAT>();
        }
    
        public int ID { get; set; }
        public Nullable<decimal> Vlera { get; set; }
        public Nullable<System.DateTime> Krijuar { get; set; }
        public Nullable<int> KrijuarNga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GJEDHAT_PARAMETRAT> GJEDHAT_PARAMETRAT { get; set; }
    }
}

SMGJ/Controllers/LAGESHTIA_AJRITController.cs
using SMGJ.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using System.Data.Entity;

namespace SMGJ.Controllers
{   [CustomAuthorizeAttribute]
    public class LAGESHTIA_AJRITController : BaseController
    {
        SMGJDB db = new SMGJDB();

        public async Task<ActionResult> Index()
        {
            var user = await GetUser();
            List<LAGESHTIA_AJRIT> model = db.LAGESHTIA_AJRIT.ToList();
            return View(model);
        }
        public async Task<ActionResult> Create()
        {
            var user = await GetUser();
            LAGESHTIA_AJRIT model = new LAGESHTIA_AJRIT();
            return View();
        }
        // DeleteMenu
        [HttpPost]
        public async Task<ActionResult> DeleteRecord(LAGESHTIA_AJRIT model)
        {
            var user = await GetUser();
            MessageJs returnmodel = new MessageJs();
            try
            {
                LAGESHTIA_AJRIT lageshtia = db.LAGESHTIA_AJRIT.Find(model.ID);


                var exists = db.GJEDHAT_PARAMETRAT.Where(e => e.LageshtiaID == model.ID).Any();
                if (exists)
                {
                    returnmodel.status = false;
                    returnmodel.Mesazhi = "Nuk mund ta fshini kete lageshti te ajrit, sepse ekzistojne Gjedha qe permbajne kete parameter ";
                    return Json(returnmodel, JsonRequestBehavior.DenyGet);
                }


                db.LAGESHTIA_AJRIT.Remove(lageshtia);
                await db.SaveChangesAsync();
                returnmodel.status = true;
                return Json(returnmodel, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                returnmodel.status = false;
                returnmodel.Mesazhi = "Ka ndodhur nje gabim";
                return Json(returnmodel, JsonRequestBehavior.DenyGet);
            }
        }
        public async Task<ActionResult> Edit(int? id)
        {
            var user = await GetUser();
            LAGESHTIA_AJRIT model = new LAGESHTIA_AJRIT();
            if (id != null)
            {
                model = db.LAGESHTIA_AJRIT.Find(id.Value);
            }
            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> Create(LAGESHTIA_AJRIT model)
        {
            var user = await GetUser();
            MessageJs returnmodel = new MessageJs();
            if (ModelState.IsValid)
            {
                try
                {
                    LAGESHTIA_AJRIT new_model = new LAGESHTIA_AJRIT();

                    new_model.Vlera = model.Vlera;
                    new_model.Krijuar = DateTime.Now;
                    new_model.KrijuarNga = user.ID;


                    var exists = db.LAGESHTIA_AJRIT.Where(e => e.Vlera == model.Vlera).Any();
                    if (exists)
                    {
                        returnmodel.status = false;
                        returnmodel.Mesazhi = "Keto vlera te lageshtise se ajrit ekzistojne";
                        return Json(returnmodel, JsonRequestBehavior.DenyGet);
                    }
                    db.LAGESHTIA_AJRIT.Add(new_model);
                    await db.SaveChangesAsync();
                    returnmodel.status = true;
                    returnmodel.Mesazhi = "Te dhenat u regjistruan me sukses";
                    return Json(returnmodel, JsonRequestBehavior.AllowGet);
                }
                catch
                {
                    returnmodel.status = false;
                    returnmodel.Mesazhi = "Ka ndodhur nje gabim";
                    return Json(returnmodel, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                returnmodel.status = false;
                returnmodel.Mesazhi = "Modeli nuk eshte valid";
                return Json(returnmodel, JsonRequestBehavior.DenyGet);
            }
        }


        [HttpPost]
        public async Task<ActionResult> Edit(LAGESHTIA_AJRIT model)
        {
            var user = await GetUser();
            MessageJs returnmodel = new MessageJs();
            if (ModelState.IsValid)
            {


                try
                {
                    LAGESHTIA_AJRIT new_model = db.LAGESHTIA_AJRIT.Find(model.ID);

                    new_model.ID = model.ID;
                    new_model.Vlera = model.Vlera;
                    new_model.Krijuar = DateTime.Now;
                    new_model.KrijuarNga = user.ID;
                    var exist = db.LAGESHTIA_AJRIT.Where(e => e.Vlera == model.Vlera && e.ID != model.ID).Any();
                    if (exist)
                    {
                        returnmodel.status = false;
                        returnmodel.Mesazhi = "Keto vlera te lageshtise se ajrit ekzistojne";
                        return Json(returnmodel, JsonRequestBehavior.DenyGet);
                    }
                    var exists = db.GJEDHAT_PARAMETRAT.Where(e => e.LageshtiaID == model.ID).Any();
                    if (exists)
                    {
                        returnmodel.status = false;
                        returnmodel.Mesazhi = "Nuk mund te ndryshoni kete lageshti te ajrit, sepse ekziston nje e tille";
                        return Json(returnmodel, JsonRequestBehavior.DenyGet);
                    }

                    db.Entry(new_model).State = EntityState.Modified;
                    //ruaj te dhenat
                    await db.SaveChangesAsync();
                    returnmodel.status = true;
                    returnmodel.Mesazhi = "Keto vlera te lageshtise se ajrit u ndryshuan me sukses";
                    return Json(returnmodel, JsonRequestBehavior.AllowGet);

                }
                catch
                {
                    returnmodel.status = false;
                    returnmodel.Mesazhi = "Ka ndodhur nje gabim";
                    return Json(returnmodel, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                returnmodel.status = false;
                returnmodel.Mesazhi = "Modeli nuk eshte valid";
                return Json(returnmodel, JsonRequestBehavior.DenyGet);
            }
        }

    }
}

SMGJ/Views/LAGESHTIA_AJRIT/Create.cshtml
@model SMGJ.Models.LAGESHTIA_AJRIT
@{
    ViewBag.Title = "Create";
}
<section id="page-title">
    <div class="row">
        <div class="col-sm-8">
            <h1 class="mainTitle">Regjistrimi i lagështive </h1>
        </div>
    </div>
</section>
<div class="container-fluid container-fullw bg-white">
    <div class="panel panel-white">
        <div class="panel-body">
            <form id="forma">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">
                                Përqindja<span class="symbol required" aria-required="true"></span>
                            </label>
                            @Html.TextBoxFor(m => m.Vlera, new { @class = "form-control", @placeholder = "Ndryshoni përqindjen" })

                        </div>
                    </div>

                </div>

            </form>
        </div>
        <div class="panel-footer clearfix">
            <div class="col-md-12">
                <button class="btn btn-primary btn-wide pull-right" type="button" onclick="regjistro(this)">
                    Register <i class="fa fa-arrow-circle-right"></i>
                </button>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        runValidator1 = function () {
            var form1 = $('#forma');
            var errorHandler1 = $('.errorHandler', form1);
            var successHandler1 = $('.successHandler', form1);
            $('#forma').validate({
                errorElement: "span", // contain the error msg in a span tag
                errorClass: 'help-block',
                errorPlacement: function (error, element) { // render error placement for each input type
                    if (element.attr("type") == "radio" || element.attr("type") == "checkbox") { // for chosen elements, need to insert the error after the chosen container
                        error.insertAfter($(element).closest('.form-group').children('div').children().last());
                    } else if (element.attr("name") == "dd" || element.attr("name") == "mm" || element.attr("name") == "yyyy") {
                        error.insertAfter($(element).closest('.form-group').children('div'));
                    } else {
                        error.insertAfter(element);
                        // for other inputs, just perform default behavior
                    }
                },
                ignore: "",
                rules: {
                    Emertimi: {
                        required: true
                    },
                    Vlera: {
                        required: true,
                        number: true
                    }
                },
                invalidHandler: function (event, validator) { //display error alert on form submit
                    successHandler1.hide();
                    errorHandler1.show();
                },
                highlight: function (element) {
                    $(element).closest('.help-block').removeClass('valid');
                    // display OK icon
                    $(element).closest('.form-group').removeClass('has-success').addClass('has-error').find('.symbol').removeClass('ok').addClass('required');
                    // add the Bootstrap error class to the control group
                },
                unhighlight: function (element) { // revert the change done by hightlight
                    $(element).closest('.form-group').removeClass('has-error');
                    // set error class to the control group
                },
                success: function (label, element) {
                    label.addClass('help-block valid');
                    // mark the current input as valid and display OK icon
                    $(element).closest('.form-group').removeClass('has-error').addClass('has-success').find('.symbol').removeClass('required').addClass('ok');
                },
                submitHandler: function (form) {
                    successHandler1.show();
                    errorHandler1.hide();
                    // submit form
                    //$('#form').submit();
                }
            });
        };
        var regjistro = function (btn) {
            runValidator1()
            if ($("#forma").valid() === true) {
                var obj = {
                    Vlera: $("#Vlera").val(),
                 //   Emertimi: $("#Emertimi").val(),
                };
                var url_redirect = '@Url.Action("Index", "LAGESHTIA_AJRIT")';
                $.ajax({
                    url: "@Url.Action("Create", "LAGESHTIA_AJRIT")",
                    cache: false,
                    type: "Post",
                    dataType: "json",
                    data: obj,
                    success: function (rs) {
                        if (rs.status) {
                            swal("U Insertua!", "Te dhenat u insertuan me sukses", "success");
                            window.setTimeout(function () { location.reload(url_redirect),2000 });
                        } else {
                            swal("Anulim", "E dhena ekziston", "error");
                        }
                    },
                    error: function (jqXHR, error, errorThrown) {
                        if (jqXHR.status && jqXHR.status == 400) {
                            console.log(jqXHR.responseText);
                        }
                        else {
                            swal("Gabim", "Provoni perseri", "error");
                        }
                    }
                });
            }
        }
    </script>
}

SMGJ/Views/LAGESHTIA_AJRIT/Edit.cshtml
@model SMGJ.Models.LAGESHTIA_AJRIT
@{
    ViewBag.Title = "Edit";
}
@Html.HiddenFor(y => y.ID)
<section id="page-title">
    <div class="row">
        <div class="col-sm-8">
            <h1 class="mainTitle">Editimi i lagështive</h1>
        </div>
    </div>
</section>
<div class="container-fluid container-fullw bg-white">
    <div class="panel panel-white">
        <div class="panel-body">
            <form id="forma">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">
                                Përqindja<span class="symbol required" aria-required="true"></span>
                            </label>
                            @Html.TextBoxFor(y => y.Vlera, new { @class = "form-control", @placeholder = "Ndryshoni përqindjen" })
                        </div>
                    </div>
                    <div class="col-md-6">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <div class="form-group">
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <div class="col-md-12">
                                <div class="checkbox clip-check check-primary">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="panel-footer clearfix">
            <div class="col-md-12">
                <button class="btn btn-primary btn-wide pull-right" type="button" onclick="edito(this)">
                    Register <i class="fa fa-arrow-circle-right"></i>
                </button>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>

        runValidator1 = function () {
            var form1 = $('#forma');
            var errorHandler1 = $('.errorHandler', form1);
            var successHandler1 = $('.successHandler', form1);
            $('#forma').validate({
                errorElement: "span", // contain the error msg in a span tag
                errorClass: 'help-block',
                errorPlacement: function (error, element) { // render error placement for each input type
                    if (element.attr("type") == "radio" || element.attr("type") == "checkbox") { // for chosen elements, need to insert the error after the chosen container
                        error.insertAfter($(element).closest('.form-group').children('div').children().last());
                    } else if (element.attr("name") == "dd" || element.attr("name") == "mm" || element.attr("name") == "yyyy") {
                        error.insertAfter($(element).closest('.form-group').children('div'));
                    } else {
                        error.insertAfter(element);
                        // for other inputs, just perform default behavior
                    }
                },
                ignore: "",
                rules: {
                  Vlera: {
                        required: true,
                        number: true
                    },
                    Emertimi: {
                        require: true
                    }

                },
                invalidHandler: function (event, validator) { //display error alert on form submit
                    successHandler1.hide();
                    errorHandler1.show();
                },
                highlight: function (element) {
                    $(element).closest('.help-block').removeClass('valid');
                    // display OK icon
                    $(element).closest('.form-group').removeClass('has-success').addClass('has-error').find('.symbol').removeClass('ok').addClass('required');
                    // add the Bootstrap error class to the control group
                },
                unhighlight: function (element) { // revert the change done by hightlight
                    $(element).closest('.form-group').removeClass('has-error');
                    // set error class to the control group
                },
                success: function (label, element) {
                    label.addClass('help-block valid');
                    // mark the current input as valid and display OK icon
                    $(element).closest('.form-group').removeClass('has-error').addClass('has-success').find('.symbol').removeClass('required').addClass('ok');
                },
                submitHandler: function (form) {
                    successHandler1.show();
                    errorHandler1.hide();
                    // submit form
                    //$('#form').submit();
                }
            });
        };
        var edito = function (btn) {
            runValidator1()
            if ($("#forma").valid() === true) {
                var obj = {
                    Vlera: $("#Vlera").val(),
                    Emertimi: $("#Emertimi").val(),
                };
                var url_redirect = '@Url.Action("Index", "LAGESHTIA_AJRIT")';
                $.ajax({
                    url: "@Url.Action("edit", "LAGESHTIA_AJRIT")",
                    cache: false,
                    type: "Post",
                    dataType: "json",
                    data: obj,
                    success: function (rs) {
                        if (rs.status) {
                            swal("U Insertua!", "Te dhenat u insertuan me sukses", "success");
                            window.location.href = url_redirect;
                        } else {
                            swal("Anulim", "E dhena ekziston", "error");
                        }
                    },
                    error: function (jqXHR, error, errorThrown) {
                        if (jqXHR.status && jqXHR.status == 400) {
                            console.log(jqXHR.responseText);
                        }
                        else {
                            swal("Gabim", "Provoni perseri", "error");
                        }
                    }
                });
            }
        }
    </script>
}

SMGJ/Views/LAGESHTIA_AJRIT/Index.cshtml
@model IEnumerable<SMGJ.Models.LAGESHTIA_AJRIT>
   @using SMGJ.Models;
@{
    ViewBag.Title = "Index";
      SMGJDB db = new SMGJDB();
}


<section id="page-title">
    <div class="row">
        <div class="col-sm-8">
            <h1 class="mainTitle">Lagështia e ajrit</h1>
        </div>
    </div>
</section>
<div class="container-fluid container-fullw bg-white">
    <div class="row">
        <div class="col-md-12">
            <a href="@Url.Action("Create","LAGESHTIA_AJRIT")" class="btn btn-green">Regjistro</a>
        </div>
    </div>
    <div class="row margin-top-15 ">
        <div class="col-md-12">
            <div class="panel panel-white">
                <div class="panel-heading">
                    <h5 class="panel-title">Lista e lagështive të ajrit </h5>
                </div>
                <div class="panel-body">
                    <table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
                        <thead>
                            <tr>
                                
                                <th class="hidden-xs">Vlera</th>
                                <th>
                                    Krijuar
                                </th>
                                <th class="hidden-xs">Krijuar e nga</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {var user = db.USERs.Find(item.KrijuarNga);
                                <tr>
                                    
                                    <td class="hidden-xs">
                                        @item.Vlera
                                    </td>
                                    <td>@item.Krijuar</td>
                                    <td>@user.Emri @user.Mbiemri</td>
                                    <td>
                                        <div class="visible-md visible-lg hidden-sm hidden-xs">

                                            <a href="@Url.Action("Edit","LAGESHTIA_AJRIT" , new {id=item.ID})" class="btn btn-transparent btn-xs" tooltip-placement="top" tooltip="Edit"><i class="fa fa-pencil"></i></a>
                                            <a onclick="deletemenu(this)" data-menuid="@item.ID" class="btn btn-transparent btn-xs tooltips" tooltip-placement="top" tooltip="Remove"><i class="fa fa-times fa fa-white"></i></a>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>

        var deletemenu = function (btn) {

            swal({
                title: "A je i Sigurt?",
                text: "Te dhenat nuk mund te kthehen!!!",
                type: "warning",
                timer: 1000000,
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Po, fshij!",
                cancelButtonText: "Anulo!",
                closeOnConfirm: false,
                closeOnCancel: false,
                await: true
            },
                function (isConfirm) {
                        if (isConfirm) {
                            var obj = { ID: $(btn).data("menuid") };
                            $.ajax({
                                url: "@Url.Action("DeleteRecord", "LAGESHTIA_AJRIT")",
                                cache: false,
                                type: "Post",
                                dataType: "json",
                                data: obj,
                                success: function (rs) {
                                    if (rs.status) {
                                        swal("U fshine!", "Te dhenat u fshin me sukses", "success");
                                        window.setTimeout(function () { location.reload() }, 2000);
                                    } else {
                                        swal("Anulim", "Te dhenat nuk jan fshire", "error");
                                    }
                                },
                                error: function (jqXHR, error, errorThrown) {
                                    if (jqXHR.status && jqXHR.status == 400) {
                                        console.log(jqXHR.responseText);
                                    }
                                    else {
                                        swal("Gabim gjate fshirjes", "Provoni perseri", "error");
                                    }
                                }
                            }); //end ajax
                        } else {
                            swal("Anulim", "Te dhenat nuk jane fshire :)", "error");
                        }
                    });
        }; //end delete

                        //end ajax

       //end delete





    </script>


}