SMGJ/Models/RACA.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMGJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RACA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RACA()
        {
            this.GJEDHIs = new HashSet<GJEDHI>();
        }
    
        public int ID { get; set; }
        public string Emertimi { get; set; }
        public Nullable<System.DateTime> Krijuar { get; set; }
        public Nullable<int> KrijuarNga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GJEDHI> GJEDHIs { get; set; }
    }
}

SMGJ/Controllers/RACAController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using SMGJ.Models;

namespace SMGJ.Controllers
{
    [CustomAuthorizeAttribute]
    public class RACAController : BaseController
    {
        SMGJDB db = new SMGJDB();
        // GET: RACA
        public ActionResult Index()
        {
            List<RACA> model = db.RACAs.ToList();
            return View(model);
        }
        public async Task<ActionResult> Create()
        {
            var user = await GetUser();
            RACA model = new RACA();
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Create(RACA r)
        {
            var user = await GetUser();
            MessageJs returnmodel = new MessageJs();
            RACA ra = new RACA();
            if (r.ID != 0)
            {
                ra = db.RACAs.Find(r.ID);
            }
            ra.Emertimi = r.Emertimi;
            ra.Krijuar = DateTime.Now;
            ra.KrijuarNga = user.ID;

            var exist = db.RACAs.Where(e => e.Emertimi.ToLower().Trim() == r.Emertimi.ToLower().Trim()).Any();
            if (exist)
            {
                returnmodel.status = false;
                returnmodel.Mesazhi = "Këto raca ekzistojnë!";
                return Json(returnmodel, JsonRequestBehavior.DenyGet);
            }

            if (r.ID == 0)
            {
                db.RACAs.Add(ra);
            }
            else
            {
                db.Entry(ra).State = EntityState.Modified;
            }

            await db.SaveChangesAsync();
            returnmodel.status = true;
            returnmodel.Mesazhi = " Raca u regjistrua me sukses";
            return Json(returnmodel, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public async Task<ActionResult> DeleteRaca(RACA model)
        {
                var user = await GetUser();
                MessageJs returnmodel = new MessageJs();
                var existsGjedhi = await db.GJEDHIs.AnyAsync(x => x.RacaID == model.ID);

            if (existsGjedhi)
                {
                    returnmodel.status = false;
                    returnmodel.Mesazhi = "Raca e gjedhit nuk mund të fshihet";
                    return Json(returnmodel, JsonRequestBehavior.DenyGet);
                }
                try
                {
                    RACA raca = db.RACAs.Find(model.ID);
                    db.RACAs.Remove(raca);
                    await db.SaveChangesAsync();
                    returnmodel.status = true;
                    returnmodel.Mesazhi = "Raca e gjedhit është fshirë me sukses";
                    return Json(returnmodel, JsonRequestBehavior.AllowGet);
                }
                catch (Exception)
                {
                    returnmodel.status = false;
                    returnmodel.Mesazhi = "Ka ndodhur një gabim";
                    return Json(returnmodel, JsonRequestBehavior.DenyGet);
                }
            }


            public async Task<ActionResult> Edit(int? id)
        {
            var user = await GetUser();
            RACA model = new RACA();
            if (id != null)
            {
                model = db.RACAs.Find(id.Value);
            }
            return View(model);
        }

        [HttpPost]

        public async Task<ActionResult> Edit(RACA model)
        {
            var user = await GetUser();
            MessageJs returnmodel = new MessageJs();

            var exists = db.GJEDHIs.Any(x => x.RacaID == model.ID);
            if (exists)
            {
                returnmodel.status = false;
                returnmodel.Mesazhi = "Nuk mund ta ndryshoni, sepse ekziston Gjedh qe e permban kete lloj te races";
                return Json(returnmodel, JsonRequestBehavior.DenyGet);
            }
            if (ModelState.IsValid)
            {
                try
                {
                    RACA new_model = db.RACAs.Find(model.ID);

                    new_model.Emertimi = model.Emertimi;
                    new_model.Krijuar = DateTime.Now;
                    new_model.KrijuarNga = user.ID;
                    db.Entry(new_model).State = EntityState.Modified;
                    //ruaj te dhenat
                    await db.SaveChangesAsync();
                    returnmodel.status = true;
                    returnmodel.Mesazhi = "Vlera u ndryshua me sukses";
                    return Json(returnmodel, JsonRequestBehavior.AllowGet);
                   
                }
                catch
                {
                    returnmodel.status = false;
                    returnmodel.Mesazhi = "Ka ndodhur nje gabim";
                    return Json(returnmodel, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                returnmodel.status = false;
                returnmodel.Mesazhi = "Modeli nuk eshte valid";
                return Json(returnmodel, JsonRequestBehavior.DenyGet);
            }
        }

    }
}




SMGJ/Views/RACA/Create.cshtml
@model SMGJ.Models.RACA

@{
    ViewBag.Title = "Create";

}
<body>
    <section id="page-title">
        <div class="row">
            <div class="col-sm-8">
                <h1 class="mainTitle" style="color:royalblue; font-family: Shakespeare, 'Times New Roman', Times, serif">Regjistrimi i Races</h1>
            </div>
        </div>
    </section>
    <div class="container-fluid container-fullw bg-white">
        <div class="panel panel-white">
            <div class="panel-body">
                <form id="forma">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">
                                    Emertimi <span class="symbol required" aria-required="true"></span>
                                </label>
                                @Html.TextBoxFor(m => m.Emertimi, new { @class = "form-control", @placeholder = "Shkruani llojin e races" })

                            </div>
                        </div>
                       
                    </div>
                  
                </form>
            </div>
            <div class="panel-footer clearfix">
                <div class="col-md-12">
                    <button class="btn btn-primary btn-wide pull-right" type="button" onclick="regjistro(this)">
                        Regjistro <i class="fa fa-arrow-circle-right"></i>
                    </button>
                    <a href="@Url.Action("Index","RACA")" class="btn btn-danger btn-wide">Anulo <i class="fa fa-arrow-circle-left"></i></a>
                </div>
            </div>
        </div>
    </div>
    @section Scripts{
        <script>
        runValidator1 = function () {
            var form1 = $('#forma');
            var errorHandler1 = $('.errorHandler', form1);
            var successHandler1 = $('.successHandler', form1);
            $('#forma').validate({
                errorElement: "span", // contain the error msg in a span tag
                errorClass: 'help-block',
                errorPlacement: function (error, element) { // render error placement for each input type
                    if (element.attr("type") == "radio" || element.attr("type") == "checkbox") { // for chosen elements, need to insert the error after the chosen container
                        error.insertAfter($(element).closest('.form-group').children('div').children().last());
                    } else if (element.attr("name") == "dd" || element.attr("name") == "mm" || element.attr("name") == "yyyy") {
                        error.insertAfter($(element).closest('.form-group').children('div'));
                    } else {
                        error.insertAfter(element);
                        // for other inputs, just perform default behavior
                    }
                },
                ignore: "",
                rules: {
                    Emertimi: {
                        required: true
                    },
                    
                },
                invalidHandler: function (event, validator) { //display error alert on form submit
                    successHandler1.hide();
                    errorHandler1.show();
                },
                highlight: function (element) {
                    $(element).closest('.help-block').removeClass('valid');
                    // display OK icon
                    $(element).closest('.form-group').removeClass('has-success').addClass('has-error').find('.symbol').removeClass('ok').addClass('required');
                    // add the Bootstrap error class to the control group
                },
                unhighlight: function (element) { // revert the change done by hightlight
                    $(element).closest('.form-group').removeClass('has-error');
                    // set error class to the control group
                },
                success: function (label, element) {
                    label.addClass('help-block valid');
                    // mark the current input as valid and display OK icon
                    $(element).closest('.form-group').removeClass('has-error').addClass('has-success').find('.symbol').removeClass('required').addClass('ok');
                },
                submitHandler: function (form) {
                    successHandler1.show();
                    errorHandler1.hide();
                  
                }
            });
        };
        var regjistro = function (btn) {

                runValidator1();
                if ($("#forma").valid() === true) {
                    var obj = {
                        Emertimi: $("#Emertimi").val(),
                        Krijuar: $("#Krijuar").val(),
                        KrijuarNga: $("#KrijuarNga").val()
                   
                };
                var url_redirect = '@Url.Action("Index", "RACA")';
                $.ajax({
                    url: "@Url.Action("Create", "RACA")",
                    cache: false,
                    type: "POST",
                    dataType: "json",
                    data: obj,
                    success: function (rs) {
                        if (rs.status) {
                            swal({ title: "U regjistrua!", text: "Raca eshte regjistruar me sukses!", type: "success" }, function () {
                                //location.reload()
                                window.location.href = url_redirect;

                            });

                        }
                        else {
                            
                            swal("Gabim në regjistrim!", rs.Mesazhi, "error");
                        }

                    },
                    error: function (jqXHR, error, errorThrown) {
                        if (jqXHR.status && jqXHR.status == 400) {
                            
                            swal("Anulim!","Ka ndodhur një problem në regjistrim! Ju lutemi provoni përsëri!","error")
                            console.log(jqXHR.responseText);
                        } else {
                            console.log("Something went wrong");
                        }
                    }
                });
            }

            };

       
        </script>

        <script src="~/Content/theme/vendor/sweetalert/sweet-alert.min.js"></script>

        <script src="~/Content/theme/vendor/select2/select2.min.js"></script>
        <script>
            jQuery(document).ready(function () {

                $(".select2").select2(
                    {
                        width: '100%'
                    });
            })
        </script>
    }
</body>

SMGJ/Views/RACA/Edit.cshtml
@model SMGJ.Models.RACA
@{
    ViewBag.Title = "Edit";
    
}
@Html.HiddenFor(k => k.ID)
<head>
    <link href="~/Content/theme/vendor/sweetalert/sweet-alert.css" rel="stylesheet" media="screen">
    <link href="~/Content/theme/vendor/sweetalert/ie9.css" rel="stylesheet" media="screen">
    <link href="~/Content/theme/vendor/toastr/toastr.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/theme/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
</head>
<section id="page-title">
    <div class="row">
        <div class="col-sm-8">
            <h1 class="mainTitle" style="color:royalblue; font-family: Shakespeare, 'Times New Roman', Times, serif">Ndryshimi i races</h1>
        </div>
    </div>
</section>
<div class="container-fluid container-fullw bg-white">
    <div class="panel panel-white">
        <div class="panel-body">
            <form id="forma">

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">
                                Emertimi <span class="symbol required" aria-required="true"></span>
                            </label>
                            @Html.TextBoxFor(k => k.Emertimi, new { @class = "form-control", @placeholder = "Shkruani vlerën e races" })

                        </div>
                    </div>
                    
                </div>
            </form>
        </div>
        <div class="panel-footer clearfix">
            <div class="col-md-12">
                <button class="btn btn-primary btn-wide pull-right" type="button" onclick="edito(this)"> Ndrysho<i class="fa fa-arrow-circle-right"></i>
                </button>
   
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        runValidator1 = function () {
            var form1 = $('#forma');
            var errorHandler1 = $('.errorHandler', form1);
            var successHandler1 = $('.successHandler', form1);
            $('#forma').validate({
                errorElement: "span", // contain the error msg in a span tag
                errorClass: 'help-block',
                errorPlacement: function (error, element) { // render error placement for each input type
                    if (element.attr("type") == "radio" || element.attr("type") == "checkbox") { // for chosen elements, need to insert the error after the chosen container
                        error.insertAfter($(element).closest('.form-group').children('div').children().last());
                    } else if (element.attr("name") == "dd" || element.attr("name") == "mm" || element.attr("name") == "yyyy") {
                        error.insertAfter($(element).closest('.form-group').children('div'));
                    } else {
                        error.insertAfter(element);
                        // for other inputs, just perform default behavior
                    }
                },
                ignore: "",
                rules: {
                    Emertimi: {
                        required: true
                    },
                    
                },
                invalidHandler: function (event, validator) { //display error alert on form submit
                    successHandler1.hide();
                    errorHandler1.show();
                },
                highlight: function (element) {
                    $(element).closest('.help-block').removeClass('valid');
                    // display OK icon
                    $(element).closest('.form-group').removeClass('has-success').addClass('has-error').find('.symbol').removeClass('ok').addClass('required');
                    // add the Bootstrap error class to the control group
                },
                unhighlight: function (element) { // revert the change done by hightlight
                    $(element).closest('.form-group').removeClass('has-error');
                    // set error class to the control group
                },
                success: function (label, element) {
                    label.addClass('help-block valid');
                    // mark the current input as valid and display OK icon
                    $(element).closest('.form-group').removeClass('has-error').addClass('has-success').find('.symbol').removeClass('required').addClass('ok');
                },
                submitHandler: function (form) {
                    successHandler1.show();
                    errorHandler1.hide();
                    // submit form
                    //$('#form').submit();
                }
            });
        };
        var edito = function (btn) {
                runValidator1();
                if ($("#forma").valid() === true) {
                    var obj = {
                        Emertimi: $("#Emertimi").val(),  
                        Krijuar: $("#Krijuar").val(),
                        KrijuarNga: $("#KrijuarNga").val()
                };
                var url_redirect = '@Url.Action("Index", "RACA")';
                $.ajax({
                    url: "@Url.Action("Edit", "RACA")",
                    cache: false,
                    type: "POST",
                    dataType: "json",
                    data: obj,
                    success: function (rs) {
                        if (rs.status) {
                            swal({ title: "U ndryshua!", text: "Raca që keni zgjedhur është ndryshuar me sukses!", type: "success" }, function () {
                                //location.reload()
                                window.location.href = url_redirect;

                            });
                        }
                        else {
                            //alert(rs.Mesazhi, "error");
                            swal("Gabim në ndryshim", rs.Mesazhi, "error");
                        }

                    },
                    error: function (jqXHR, error, errorThrown) {
                        if (jqXHR.status && jqXHR.status == 400) {
                            console.log(jqXHR.responseText);
                            swal("Anulim!", "Ka ndodhur një problem në ndryshim! Ju lutemi provoni përsëri!", "error")
                        } else {
                            swal("Anulim!", "Ka ndodhur një problem në ndryshim! Ju lutemi provoni përsëri!", "error")
                            console.log("Something went wrong");
                        }
                    }
                });
            }

        };


    </script>
    <script src="~/Content/theme/vendor/sweetalert/sweet-alert.min.js"></script>
    <script src="~/Content/theme/vendor/toastr/toastr.min.js"></script>
    <script src="~/Content/theme/assets/js/main.js"></script>
    <script src="~/Content/theme/assets/js/ui-notifications.js"></script>
    <script src="~/Content/theme/vendor/select2/select2.min.js"></script>
    <link href="~/Content/theme/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
    <script>
        jQuery(document).ready(function () {

            $(".select2").select2(
                {
                    width: '100%'
                });
        })
    </script>

}


SMGJ/Views/RACA/Index.cshtml
@model IEnumerable<SMGJ.Models.RACA>
@using SMGJ.Models
@{
    ViewBag.Title = "Index";
    SMGJDB db = new SMGJDB();
}
<section id="page-title">
    <div class="row">
        <div class="col-md-12">
            <h1 class="mainTitle text-center">RACA</h1>
        </div>
    </div>
</section>

<div class="container-fluid container-fullw bg-white">
    <div class="row">
        <div class="col-md-12">
            <a href="@Url.Action("Create","RACA")" class="btn btn-green">Regjistro</a>
        </div>
    </div>
    <div class="row margin-top-15 ">
        <div class="col-md-12">
            <div class="panel panel-white">
                <div class="panel-heading">
                    <h5 class="panel-title">Lista e Racave </h5>
                </div>
                <div class="panel-body">
                    <table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
                        <thead>
                            <tr>

                                <th>Em&euml;rtimi</th>
                                <th>Krijuar</th>
                                <th class="hidden-xs"> Krijuar nga</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                var user = db.USERs.Find(item.KrijuarNga);
                                <tr>

                                    <td class="hidden-xs">
                                        @item.Emertimi
                                    </td>
                                    <td>@item.Krijuar</td>
                                    <td>@user.Emri @user.Mbiemri</td>
                                    <td>
                                        <div class="visible-md visible-lg hidden-sm hidden-xs">
                                            <a href="@Url.Action("Edit", "RACA", new { id = item.ID })" class="btn btn-transparent btn-xs" tooltip-placement="top" tooltip="Edit"><i class="fa fa-pencil"></i></a>
                                            <a onclick="deleteraca(this)" data-menuid="@item.ID" class="btn btn-transparent btn-xs tooltips" tooltip-placement="top" tooltip="Remove"><i class="fa fa-times fa fa-white"></i></a>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
</div>

@section Scripts{
    <script>
        var deleteraca = function (btn) {
            var obj = { ID: $(btn).data("menuid") };
            swal({
                title: "Kujdes!!!",
                text: "Jeni duke fshire të dhëna nga sistemi",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "PO!",
                cancelButtonText: "JO!",
                closeOnConfirm: false,
                closeOnCancel: false
            }, function (isConfirm) {
                    if (isConfirm) {
                    $.ajax({
                    url: "@Url.Action("DeleteRaca", "RACA")",
                    cache: false,
                    type: "POST",
                    dataType: "json",
                    data: obj,
                    success: function (rs) {
                        if (rs.status) {
                            swal({ title: "Fshire", text: rs.Mesazhi, type: "success" },
                                function () {
                                    location.reload();
                                }
                            );
                        }
                        else {
                            swal("Gabim!",
                                rs.Mesazhi,
                                "info");
                        }
                    },
                    error: function (jqXHR, error, errorThrown) {
                        if (jqXHR.status && jqXHR.status == 400) {
                            console.log(jqXHR.responseText);
                        } else {
                            console.log("Something went wrong");
                        }
                    }
                });
                } else {
                    swal("Gabim", "Fshirja e te dhenave eshte anuluar :)", "error");
                }
            });
        };
    </script>
}